# Generated by Django 5.2.5 on 2025-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcheckincode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
