# Generated by Django 4.2.23 on 2025-09-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_leaderrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderRequest',
        ),
    ]
